### ISSUE TITLE
Naming Option for "Add Animation Node"

### ISSUE THREAD

**Issue by ikonnow** [brickengineer/BCRYExporter#2]
**Issue description:**
when creating an animation, there is only one option for naming. this is not always the intended workflow.

**Steps to reproduce
click on Add Animation Node, enter a name

**Intended behavior:**
For animation name respect / not respect meshname checkbox.

**Comment by brickengineer** [comment]
Could you explain this issue more with more details? I don't quite understand how the _Add Animation Node_ function are supposed to work according to your artists?
