### ISSUE TITLE
Average position for "Add Branch"

### ISSUE THREAD

**Issue by ikonnow** [brickengineer/BCRYExporter#3]
**Description of the problem:**
Add branch creates a "branch" at the active / first vertex point, this is not always the intended workflow. 

**Steps to Reproduce:**
Select multiple vertex points (or edges / faces) in Cry Utilities click "Add Branch".

**Intended behavior:**
Especially if an edge, a loop or a face was selected, it makes sense to get an "average position" between the vertex points selected with it. This function could be added with SHIFT or ALT + click.

**Comment by brickengineer** [comment]
Users are supposed to add branches at exact vertex points. See _**Adding the Helper Dummies**_ at https://docs.cryengine.com/display/CEMANUAL/Vegetation+04+Bushes+%28Touch+Bending%29+3dsMax
