### ISSUE TITLE
Proxy "cube" issue

### ISSUE THREAD

**Issue by ikonnow** [brickengineer/BCRYExporter#4]
**Issue description:**
The proxy creation function is not 100% functional / "visibly" works only for cubes. There are more basic shapes but they are not created according to the shape - even if you manipulate the proxymesh.
all proxies capsule cylinder spere become "box" after clicking the respective option 

**Steps to reproduce:**
In Cry Utilities click on the respective options (capsule cylinder spere). After a mesh has been created and packed into an export node.

**Intended behavior:**
Just as the "box" option creates a cube that adapts to the mesh, this should also be possible for the other shapes.

**Comment by brickengineer** [comment]
This feature does work as expected. Users can only see a "box" when add sphere or cylinder primitive proxies. But the cube only indicates the sphere/cylinder's range, what really matters are custom properties set to them. They will be converted into sphere/cylinder primitive proxies when export to the CryEngine.
The only inconvenience here is that users need to adjust the box's size a little bit for cylinders/sphere.
